### ISSUE TITLE
FAQ Redirect instead of 404

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/website#28]
In the currently distributed toolkit pages (and previous versions) we have a **FAQs** link in the Help menu (top-right) that links to https://www.perfsonar.net/about/faq/

That URL is currently a 404 where it should be a redirect to https://docs.perfsonar.net/FAQ.html

**Comment by tonin** [comment]
See https://github.com/perfsonar/toolkit/issues/403 for a permanent change in the toolkit. But we still need the redirect for current and older versions of toolkit.

**Comment by szymontrocha** [comment]
The currently supported versions of pS contain correct link.
