### ISSUE TITLE
Add a static ls.cache.hints file to root of website

### ISSUE THREAD

**Issue by arlake228** [perfsonar/website#29]
The perfSONAR web site needs a static file at https://www.perfsonar.net/ls.cache.hints. The file will have one line:
```
http://ps-west.es.net/cache.tgz
```

It seems just adding it to the pages subdirectory is not enough to get it added.

**Comment by mfeit-internet2** [comment]
This is done.  For future reference, this is how to generate a plain text file in Jekyll:

```
---
layout: none
permalink: ls.cache.hints
---
http://ps-west.es.net/cache.tgz
```

```
$ curl -s https://www.perfsonar.net/ls.cache.hints
http://ps-west.es.net/cache.tgz
```
